services:
  - type: web
    name: mjvc-attendance
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install --legacy-peer-deps --include=dev && npx prisma generate && npm run build
    startCommand: npx prisma db push --accept-data-loss && npm run db:seed && npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mjvc-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_APP_NAME
        value: "MJVC EA's Jesús"
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production

databases:
  - name: mjvc-db
    plan: free
    databaseName: mjvc_attendance
    user: mjvc_user
    region: oregon
